# Generated by Django 2.2.17 on 2020-11-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GGG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvcgfdgfdghfytf', models.BigIntegerField()),
                ('jhguguigjggjhgkjghkjhgk', models.BigIntegerField()),
                ('hgfhfhg', models.GenericIPAddressField(protocol='IPv6')),
                ('bvcbcb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ggg_bvcbcb', to='home.CustomText')),
                ('bvhgfhg', models.ManyToManyField(related_name='ggg_bvhgfhg', to='home.HomePage')),
            ],
        ),
    ]
